//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FzDataBase.SunnyTeach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Order()
        {
            this.Tb_UserScheme = new HashSet<Tb_UserScheme>();
        }
    
        public string ID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> SchoollID { get; set; }
        public string AdminAccount { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public string SchemeName { get; set; }
        public Nullable<int> OrderMon { get; set; }
        public Nullable<int> SchemeNum { get; set; }
        public Nullable<int> AccessNum { get; set; }
        public Nullable<decimal> SchemeMoney { get; set; }
        public Nullable<int> OptType { get; set; }
        public string SchemeStateNm { get; set; }
        public Nullable<int> SchemeTypeID { get; set; }
        public string SchemeTypeName { get; set; }
        public string SchemeNo { get; set; }
        public Nullable<System.DateTime> SchemeDate { get; set; }
        public string Ecordercode { get; set; }
        public Nullable<int> Trial { get; set; }
        public string BossOrderID { get; set; }
        public Nullable<long> CustID { get; set; }
        public string CustCode { get; set; }
        public Nullable<int> CustType { get; set; }
        public Nullable<int> RegisterSource { get; set; }
        public string Email { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> BeginTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public string CustName { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserLias { get; set; }
        public string Produectparas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_UserScheme> Tb_UserScheme { get; set; }
    }
}
