//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FzDataBase.SunnyTeach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_UserScheme
    {
        public long UserID { get; set; }
        public string ID { get; set; }
        public string UserName { get; set; }
        public string Useralias { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<long> BeginTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public string ApplyNo { get; set; }
        public string EcorderCode { get; set; }
        public Nullable<long> CustID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> OptType { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Paras { get; set; }
        public Nullable<int> UserType { get; set; }
    
        public virtual Tb_Order Tb_Order { get; set; }
    }
}
